name: clusterGAN
channels:
  - pytorch
  - defaults
dependencies:
  - asttokens=2.0.5
  - backcall=0.2.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.07.19
  - certifi=2022.6.15
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - colorama=0.4.5
  - cryptography=37.0.1
  - cudatoolkit=11.3.1
  - cycler=0.11.0
  - debugpy=1.5.1
  - decorator=5.1.1
  - entrypoints=0.4
  - executing=0.8.3
  - fonttools=4.25.0
  - freetype=2.10.4
  - glib=2.69.1
  - gst-plugins-base=1.18.5
  - gstreamer=1.18.5
  - icu=58.2
  - idna=3.3
  - intel-openmp=2021.4.0
  - ipykernel=6.9.1
  - ipython=8.4.0
  - jedi=0.18.1
  - jpeg=9e
  - jupyter_client=7.2.2
  - jupyter_core=4.10.0
  - kiwisolver=1.4.2
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libdeflate=1.8
  - libffi=3.4.2
  - libiconv=1.16
  - libogg=1.3.5
  - libpng=1.6.37
  - libsodium=1.0.18
  - libtiff=4.4.0
  - libuv=1.40.0
  - libvorbis=1.3.7
  - libwebp=1.2.2
  - libxml2=2.9.14
  - libxslt=1.1.35
  - lz4-c=1.9.3
  - matplotlib=3.5.2
  - matplotlib-base=3.5.2
  - matplotlib-inline=0.1.2
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - nest-asyncio=1.5.5
  - ninja=1.10.2
  - ninja-base=1.10.2
  - numpy=1.23.1
  - numpy-base=1.23.1
  - openssl=1.1.1q
  - packaging=21.3
  - parso=0.8.3
  - pcre=8.45
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pip=22.1.2
  - ply=3.11
  - prompt-toolkit=3.0.20
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.11.2
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pysocks=1.7.1
  - python=3.10.4
  - python-dateutil=2.8.2
  - pytorch=1.12.1
  - pytorch-mutex=1.0=cuda
  - pyzmq=23.2.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - requests=2.28.1
  - setuptools=63.4.1
  - sip=6.6.2
  - six=1.16.0
  - sqlite=3.39.2
  - stack_data=0.2.0
  - tk=8.6.12
  - toml=0.10.2
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - tornado=6.1
  - traitlets=5.1.1
  - typing_extensions=4.3.0
  - tzdata=2022a
  - urllib3=1.26.11
  - wcwidth=0.2.5
  - wheel=0.37.1
  - xz=5.2.5
  - zeromq=4.3.4
  - zlib=1.2.12
  - zstd=1.5.2
